### ISSUE TITLE
CONTRIBUTED? COME HERE!

### ISSUE THREAD

**Issue by imdevarsh** [webdev03/smartpage#1]
If you've contributed to the smartpage project, read this!
So, to add your contribution to the readme, post this
```@all-contributors add <GitHub username> for <contributions>```

`<Github username>` is your username on Github.
`<contributions>` is one of the contributions on the [emoji key](https://allcontributors.org/docs/en/emoji-key).

**Comment by imdevarsh** [comment]
@all-contributors add @webdev03 for projectManagement, code

**Comment by hello-smile6** [comment]
@all-contributors add @hello-smile6 for code, content, design, ideas

> 

I was getting it... :(

**Comment by imdevarsh** [comment]
wait I'll do it
edit: nevermind

**Comment by imdevarsh** [comment]
@all-contributors add @hello-smile6 for code, content, design, ideas
