### ISSUE TITLE
UI looks bad (spacing and scrollbars)

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/smartpage#5]
https://smartpage-rm9gwv0jv-webdev03.vercel.app/

**Comment by imdevarsh** [comment]
Not very constructive

**Comment by imdevarsh** [comment]
Also there are no scrollbars?

**Comment by hello-smile6** [comment]
It doesn't fill the whole page.
![image](https://user-images.githubusercontent.com/73048226/147896643-0b21130e-1222-4f8f-b8d1-f64446fff7a3.png)

**Comment by imdevarsh** [comment]
So you want it aligned?

**Comment by hello-smile6** [comment]
> So you want it aligned?

Think I might be able to fix it, wait a moment. What's the command to install with pnpm?

**Comment by imdevarsh** [comment]
`pnpm install`
